services:
  - type: web
    name: jss-attendance-portal
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jss-postgres-db
          property: connectionString

databases:
  - name: jss-postgres-db
    plan: free
